# Generated by Django 2.1.2 on 2018-10-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_auto_20181009_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuetracker.Customers'),
        ),
    ]
